import HomePage from "./homePage"
import ProductPage from "./productPage"
import ArchivePage from "./archivePage"
import CartPage from "./cartPage"
import SuccessPage from "./successPage"
import OrdersPage from "./ordersPage"
import SearchPage from "./searchPage"
import ErrorPage from "./errorPage"
import GuaranteePage from "./guaranteePage"
import DeliveryPage from "./deliveryPage"
import AboutPage from "./aboutPage"
import ServicePage from "./servicePage"
import OfferPage from "./offerPage"
import MaguapayPage from "./maguapayPage"

export { HomePage, ProductPage, ArchivePage, CartPage, SuccessPage, OrdersPage, SearchPage, ErrorPage, GuaranteePage, DeliveryPage, AboutPage, ServicePage, OfferPage, MaguapayPage }